# # Use the official Node.js 20 image from the Docker Hub
# FROM node:20

# # Set the working directory inside the container
# WORKDIR /voiceBackend
# # Copy package.json and package-lock.json (if present) to the working directory
# COPY package*.json ./

# # Install the project dependencies
# RUN npm install

# # Copy the rest of the application code to the working directory
# COPY . .

# # Define the command to run the application
# CMD ["npm", "run", "dev"]